sonar.projectKey=urlshortner-microservices
sonar.projectName=urlshortner-microservices
sonar.sources=go-service,node-service,python-service
sonar.sourceEncoding=UTF-8

# Optional: add exclusions to reduce noise if needed.
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/*.db
